from . import sale_order
from . import wallet
from . import res_partner
from . import auth_api_key
from . import account_invoice
from . import company
from . import res_config_settings
from . import credit_request
from . import debit_request
from . import commission_rule
from . import reconversion_rule
from . import topup_rule
from . import wallet_restriction_rule
from . import lokavaluto_private_services_collection
from . import res_alt_currency
from . import payment_request
from . import payment_request_recurrent_contract
