from dateutil.relativedelta import relativedelta

from odoo import _, api, fields, models


class PaymentRequestRecurrentContract(models.Model):
    """
    Represents the contract to generate recurrent payment requests.

    It can be created by the future sender OR the future receiver of the payments.
    Its purpose is to create all the payment requests for each period.
    """

    _name = "payment.request.recurrent.contract"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _description = "Payment request recurrent contract"

    name = fields.Char(
        string="Reference",
        required=True,
        copy=False,
        readonly=True,
        default=lambda self: _("New"),
    )
    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("open", "Running"),
            ("closed", "Closed"),
        ],
        string="Status",
        required=True,
        default="draft",
        tracking=True,
    )
    alt_currency_id = fields.Many2one(
        "res.alt.currency",
        string="Currency",
        required=True,
        tracking=True,
    )
    amount = fields.Float("Amount", required=True, tracking=True)
    creator_wallet_id = fields.Many2one(
        "res.partner.backend",
        string="Created by Wallet",
        required=True,
        tracking=True,
    )
    creator_partner_id = fields.Many2one(
        "res.partner",
        related="creator_wallet_id.partner_id",
    )
    sender_wallet_id = fields.Many2one(
        "res.partner.backend",
        string="Sender Wallet",
        required=True,
        tracking=True,
    )
    sender_partner_id = fields.Many2one(
        "res.partner",
        related="sender_wallet_id.partner_id",
    )
    receiver_wallet_id = fields.Many2one(
        "res.partner.backend",
        string="Receiver Wallet",
        required=True,
        tracking=True,
    )
    receiver_partner_id = fields.Many2one(
        "res.partner",
        related="receiver_wallet_id.partner_id",
    )

    date_start = fields.Date(
        string="Start Date",
        index=True,
        default=lambda self: fields.Date.context_today(self),
        help="Contract activation date (first recurrence starts here)",
    )
    date_end = fields.Date(
        string="End Date",
        index=True,
        help="Optional contract termination date (limits recurrence)",
    )
    recurring_next_date = fields.Date(
        string="Next Payment Request Date",
        index=True,
        copy=False,
        help="Date of the next payment request to be generated",
    )
    recurring_rule_type = fields.Selection(
        [
            ("daily", "Day(s)"),
            ("weekly", "Week(s)"),
            ("monthly", "Month(s)"),
            ("yearly", "Year(s)"),
        ],
        default="monthly",
        string="Recurrence",
        help="Specify interval for automatic payment request generation.",
    )
    recurring_interval = fields.Integer(
        default=1,
        string="Create Every",
        help="Create payment requests every (Days/Week/Month/Year)",
    )

    message = fields.Char("Message", tracking=True)

    payment_request_ids = fields.One2many(
        "payment.request",
        "recurrent_contract_id",
        string="Payment Requests",
    )
    payment_request_count = fields.Integer(
        string="Payment Request Count",
        compute="_compute_payment_request_count",
    )

    @api.depends("payment_request_ids")
    def _compute_payment_request_count(self):
        for contract in self:
            contract.payment_request_count = len(contract.payment_request_ids)

    def action_view_payment_requests(self):
        """Open the list of payment requests generated by this contract."""
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Payment Requests"),
            "res_model": "payment.request",
            "view_mode": "tree,form",
            "domain": [("recurrent_contract_id", "=", self.id)],
            "context": {"default_recurrent_contract_id": self.id},
        }

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("name", _("New")) == _("New"):
                vals["name"] = self.env["ir.sequence"].next_by_code(
                    "payment.request.recurrent.contract"
                ) or _("New")
            # Initialize recurring_next_date with date_start if not set
            if not vals.get("recurring_next_date") and vals.get("date_start"):
                vals["recurring_next_date"] = vals["date_start"]
        return super().create(vals_list)

    def action_confirm(self):
        """Confirm the contract and set it to running state."""
        for contract in self:
            if not contract.recurring_next_date:
                contract.recurring_next_date = (
                    contract.date_start or fields.Date.context_today(self)
                )
            contract.state = "open"
        return True

    def action_close(self):
        """Close the contract."""
        self.write({"state": "closed"})
        return True

    def action_draft(self):
        """Reset to draft state."""
        self.write({"state": "draft"})
        return True

    def _get_recurring_interval_delta(self):
        """Return the relativedelta based on recurring_rule_type and recurring_interval."""
        self.ensure_one()
        interval = self.recurring_interval
        rule_type = self.recurring_rule_type
        if rule_type == "daily":
            return relativedelta(days=interval)
        elif rule_type == "weekly":
            return relativedelta(weeks=interval)
        elif rule_type == "monthly":
            return relativedelta(months=interval)
        elif rule_type == "yearly":
            return relativedelta(years=interval)
        return relativedelta()

    def _prepare_payment_request_values(self):
        """Prepare values for creating a payment request from this contract."""
        self.ensure_one()
        return {
            "alt_currency_id": self.alt_currency_id.id,
            "amount": self.amount,
            "creator_wallet_id": self.creator_wallet_id.id,
            "sender_wallet_id": self.sender_wallet_id.id,
            "receiver_wallet_id": self.receiver_wallet_id.id,
            "message": self.message,
            "recurrent_contract_id": self.id,
        }

    def _create_payment_request(self):
        """Create a payment request for this contract and update next date."""
        self.ensure_one()
        PaymentRequest = self.env["payment.request"]
        values = self._prepare_payment_request_values()
        payment_request = PaymentRequest.create(values)

        # Update the next recurring date
        self.recurring_next_date = (
            self.recurring_next_date + self._get_recurring_interval_delta()
        )

        # Check if contract should be closed (end date reached)
        if self.date_end and self.recurring_next_date > self.date_end:
            self.state = "closed"
            self.message_post(
                body=_("Contract automatically closed: end date reached.")
            )

        self.message_post(
            body=_("Payment request %s created.", payment_request.display_name)
        )
        return payment_request

    @api.model
    def _cron_recurring_create_payment_requests(self):
        """
        Cron function to create recurrent payment requests from contracts.
        Searches for active contracts where the next payment request date is due.
        """
        today = fields.Date.context_today(self)

        # Find all running contracts where recurring_next_date is today or in the past
        # and where date_end is not reached (or not set)
        domain = [
            ("state", "=", "open"),
            ("recurring_next_date", "<=", today),
            "|",
            ("date_end", "=", False),
            ("date_end", ">=", today),
        ]
        contracts = self.search(domain)

        created_requests = self.env["payment.request"]
        for contract in contracts:
            try:
                payment_request = contract._create_payment_request()
                created_requests |= payment_request
            except Exception as e:
                contract.message_post(
                    body=_("Failed to create payment request: %s", str(e))
                )

        return created_requests
