from . import test_partner_services_wallet_restriction_rules
from . import test_partner_services_credit_requests
from . import test_partner_services_reconversions
from . import test_partner_services_search
from . import test_partner_services_backend_credentials
from . import test_res_alt_currency
from . import test_partner_services_report_contact_info
from . import test_tools
from . import test_payment_request_services
from . import test_payment_request_recurrent_contract
